substitutions:
  devicename: ac-living-room #記得每台要不同名稱避免打架
  upper_devicename: "Climate Living Room"
  model_name: "RAS-50NK" #可加註冷氣型號

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: ESP32 for $model_name
  project:
    name: "TaiSEIA-Hitachi.$model_name"
    version: "ESP32"

external_components:
  - source: github://tsunglung/taixia@master
    components: [ taixia ]

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome #ESPhome 2024.6以前不用這行
#web_server:

uart:
  id: uart_taixia
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  debug:
    direction: BOTH
    
    
# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"

status_led:
  pin:
    number: GPIO2 # Blue LED

climate:
  - platform: taixia
    name: "Climate"
    supported_modes:
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_fan_modes:
      - LOW
      - MEDIUM
      - HIGH
      - AUTO
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    supported_presets:
      - NONE
      - BOOST
      - ECO
    #supported_humidity: True

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"
  - platform: taixia
    type: airconditioner
    get_info:
      name: "Get Info"

number:
  - platform: taixia
    type: airconditioner
#    vertical_fan_speed:
#      name: "Vertical Fan Speed"
#      max_value: 4
    horizontal_fan_speed:
      name: "Horizontal Fan Speed"
      max_value: 4
    sleep_timer:
      name: "Sleep Timer"
    off_timer:
      name: "Off Timer"
    on_timer:
      name: "On Timer"

select:
  - platform: taixia
    type: airconditioner
    display_mode:
      name: "Display Mode"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: taixia
    type: airconditioner
    temperature_indoor:
      name: "Temperature Indoor"
    humidity_indoor:
      name: "Humidity Indoor"
    temperature_outdoor:
      name: "Temperature Outdoor"
    energy_consumption:
      name: "Energy"
    operating_hours:
      name: "Operating Hours"

switch:
  - platform: taixia
    type: airconditioner
    power:
      name: "Power Switch"
    beeper:
      name: "Buzzer"
    mildew_proof:
      name: "Mildew Proof"
    air_flow_vertical:
      name: "Vertical Fan"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
  sa_id: 1
#  max_length: 100
#  uart_id: uart_taixia

time:
  - platform: homeassistant
    id: homeassistant_time
