substitutions:
  devicename: erv-h #記得每台要不同名稱避免打架
  upper_devicename: "ERV-H"
  model_name: "ERV" #可加註冷氣型號

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: ESP32C3 for $model_name
  project:
    name: "TaiSEIA-Hitachi.$model_name"
    version: "ESP32C3"

external_components:
  - source: github://tsunglung/taixia@master
    components: [ taixia ]

esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome

web_server:

uart:
  id: uart_taixia
  tx_pin: GPIO7 #21 #pin3 (RX to AC)
  rx_pin: GPIO6 #20 #pin4 (TX from AC)
  baud_rate: 9600
  debug:
    direction: BOTH
    
    
# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"

status_led:
  pin:
    number: GPIO8 # Blue LED
    #inverted: True # C3 pro need set True

climate:
  - platform: taixia
    sa_id: 14
    name: "Climate"
    supported_modes:
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY

button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic
  - platform: restart
    name: "Restart"

number:
  - platform: taixia
    type: erv
    on_timer:
      name: "On Timer"

select:
  - platform: taixia
    type: erv
    ventilate_mode:
      name: "Ventilate Mode"
    pre_heat_cool:
      name: "Pre Heat/Cool"


sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: taixia
    type: erv
    temperature_indoor:
      name: "Temperature In"
    temperature_outdoor:
      name: "Temperature Out"


switch:
  - platform: taixia
    type: airconditioner
    power:
      name: "Power Switch"


text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
  sa_id: 14

time:
  - platform: homeassistant
    id: homeassistant_time
