substitutions:
  devicename: climate-p-lj
  upper_devicename: "Climate-P-LJ"
  model_name: "Climate"


esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: ESP32C3 for $model_name
  project:
    name: "TaiSEIA-Panasonic.LJ"
    version: "ESP32C3" #hardware

external_components:
  - source: github://xangin/taixia@master
    components: [ taixia ]
    #refresh: 0s

esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome

web_server:

uart:
  id: uart_taixia
  tx_pin: GPIO7 #pin3 (RX to AC)
  rx_pin: GPIO6 #pin4 (TX from AC)
  baud_rate: 9600
  debug:
    direction: BOTH
    
status_led:
  pin:
    number: GPIO8 # Blue LED
    
# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"
  - platform: taixia
    type: airconditioner
    get_info:
      name: "Get Info"

climate:
  - platform: taixia
    name: "Climate"
    supported_modes:
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_fan_modes:
      - LOW
      - MEDIUM
      - HIGH
      - AUTO
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    supported_presets:
      - NONE
      - BOOST
      - ECO
      - ACTIVITY
      - SLEEP
      - AWAY


number:
  - platform: taixia
    type: airconditioner
    off_timer:
      name: "Off Timer"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: taixia
    type: airconditioner
    temperature_indoor:
      name: "Temperature Indoor"
    temperature_outdoor:
      name: "Temperature Outdoor"
    operating_current:
      name: "Current"
    energy_consumption:
      state_class: total_increasing
      name: "Energy"
    operating_watt:
      name: "Power"

select:
  - platform: taixia
    type: airconditioner
    display_mode:
      name: "Display Mode"

switch:
  - platform: taixia
    type: airconditioner
    power:
      name: "Power Switch"
    beeper:
      name: "Buzzer"
    mildew_proof:
      name: "Mildew Proof"
    self_cleaning:
      name: "Self Cleaning"
      
text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
  sa_id: 1
  response_time: 6500
  
time:
  - platform: homeassistant
    id: homeassistant_time
